Changes to nightly workflow and test workflow

diff --git a/.github/workflows/on-nightly.yml b/.github/workflows/on-nightly.yml
--- a/.github/workflows/on-nightly.yml
+++ b/.github/workflows/on-nightly.yml
@@ -6,66 +6,67 @@ on:
     - cron: '0 0 * * *'
 
 jobs:
-  docker-build:
-      uses: ./.github/workflows/build-image.yml
-      secrets: inherit
-
-  build:
-    needs: docker-build
-    uses: ./.github/workflows/build.yml
-    secrets: inherit
-    with:
-      docker-image: ${{ needs.docker-build.outputs.docker-image }}
-  test_full_model_passing:
-    needs:
-      - docker-build
-      - build
-    uses: ./.github/workflows/test.yml
-    secrets: inherit
-    with:
-      test_mark: 'nightly and not xfail'
-      test_group_cnt: 4
-      test_group_ids: '[1,2,3,4]'
-      docker-image: ${{ needs.docker-build.outputs.docker-image }}
-      runs-on: '[{"runs-on": "n150"}]'
-  perf-benchmark:
-    needs:
-      - docker-build
-      - build
-    uses: ./.github/workflows/perf-benchmark.yml
-    secrets: inherit
-    with:
-      docker-image: ${{ needs.docker-build.outputs.docker-image }}
-
-  fail-notify:
-    if: always()
-    needs:
-      - docker-build
-      - build
-      - test_full_model_passing
-      - perf-benchmark
-    runs-on: Ubuntu-latest
-    outputs:
-      is-main: ${{ steps.branch-check.outputs.IS_MAIN }}
-      failed: ${{ steps.check.outputs.failure }}
+  Nightly:
+    runs-on: ubuntu-latest
     steps:
-      - name: Check if branch is main
-        id: branch-check
-        run: echo "IS_MAIN=$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
-      - name: Check if the needed jobs succeeded or failed
-        id: check
-        uses: re-actors/alls-green@release/v1
+      - id: docker-build
+        uses: ./.github/workflows/build-image.yml
+      - uses: ./.github/workflows/build.yml
         with:
-          jobs: ${{ toJSON(needs) }}
-
-  fail-send-msg:
-    if: always()
-    needs:
-      - fail-notify
-    runs-on: Ubuntu-latest
-    steps:
-      - name: Send Fail Notification
-        if: ${{ needs.fail-notify.outputs.failed == 'true' && needs.fail-notify.outputs.is-main == 'true' }}
+          docker-image: ${{ steps.docker-build.outputs.docker-image }}
+      - name: Test Full Model Passing
+        id: test_full_model_passing
+        continue-on-error: true
+        uses: ./.github/workflows/test.yml
+        with:
+          test_mark: 'nightly and not xfail'
+          test_group_cnt: 4
+          test_group_ids: '[1,2,3,4]'
+          docker-image: ${{ steps.docker-build.outputs.docker-image }}
+          runs-on: '[{"runs-on": "n150"}]'
+      - name: Perf Benchmark
+        id: perf_benchmark
+        continue-on-error: true
+        uses: ./.github/workflows/perf-benchmark.yml
+        with:
+          docker-image: ${{ steps.docker-build.outputs.docker-image }}
+      - name: Test Full Model XFailing
+        id: test_full_model_xfailing
+        continue-on-error: true
+        uses: ./.github/workflows/test.yml
+        with: 
+          test_mark: 'nightly and xfail'
+          test_group_cnt: 4
+          test_group_ids: '[1,2,3,4]'
+          docker-image: ${{ steps.docker-build.outputs.docker-image }}
+          runs-on: '[{"runs-on": "n150"}]'
+      - name: Test Models Ops
+        id: test_models_ops
+        continue-on-error: true
+        uses: ./.github/workflows/test.yml
+        with:
+          test_mark: 'nightly_models_ops'
+          test_group_cnt: 4
+          test_group_ids: '[1,2,3,4]'
+          docker-image: ${{ steps.docker-build.outputs.docker-image }}
+          runs-on: '[{"runs-on": "n150"}]'
+      - name: Test Sweeps
+        id: test_sweeps
+        continue-on-error: true
+        uses: ./.github/workflows/test.yml
+        with:
+          test_mark: 'nightly_sweeps'
+          test_group_cnt: 4
+          test_group_ids: '[1,2,3,4]'
+          docker-image: ${{ steps.docker-build.outputs.docker-image }}
+          runs-on: '[{"runs-on": "n150"}]'
+      - name: Summary
+        id: summary
+        run: |
+          echo "SUCCESS=$(if [ '${{ steps.test_full_model_passing.conclusion }}' == 'success' && '${{ steps.perf_benchmark.conclusion }}' == 'success' && '${{ steps.test_full_model_xfailing.conclusion }}' == 'success' ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
+          echo "IS_MAIN=$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
+      - name: Notify
+        if: ${{ steps.summary.outputs.SUCCESS == 'false' && steps.summary.outputs.IS_MAIN == 'true' }}
         uses: slackapi/slack-github-action@v1.26.0
         with:
           payload: |
@@ -75,3 +76,118 @@ jobs:
             }
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NIGHTLY_FAIL }}
+      - name: Fail
+        if: ${{ steps.summary.outputs.SUCCESS == 'false' }}
+        run: exit 1
+
+  # docker-build:
+  #   uses: ./.github/workflows/build-image.yml
+  #   secrets: inherit
+
+  # build:
+  #   needs: docker-build
+  #   uses: ./.github/workflows/build.yml
+  #   secrets: inherit
+  #   with:
+  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
+
+  # test_full_model_passing:
+  #   needs:
+  #     - docker-build
+  #     - build
+  #   uses: ./.github/workflows/test.yml
+  #   secrets: inherit
+  #   with:
+  #     test_mark: 'nightly and not xfail'
+  #     test_group_cnt: 4
+  #     test_group_ids: '[1,2,3,4]'
+  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
+  #     runs-on: '[{"runs-on": "n150"}]'
+
+  # perf-benchmark:
+  #   needs:
+  #     - docker-build
+  #     - build
+  #   uses: ./.github/workflows/perf-benchmark.yml
+  #   secrets: inherit
+  #   with:
+  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
+
+  # test_full_model_xfailing:
+  #   needs:
+  #     - docker-build
+  #     - build
+  #   uses: ./.github/workflows/test.yml
+  #   secrets: inherit
+  #   with:
+  #     test_mark: 'nightly and xfail'
+  #     test_group_cnt: 4
+  #     test_group_ids: '[1,2,3,4]'
+  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
+  #     runs-on: '[{"runs-on": "n150"}]'
+
+  # test_models_ops:
+  #   needs:
+  #     - docker-build
+  #     - build
+  #   uses: ./.github/workflows/test.yml
+  #   secrets: inherit
+  #   with:
+  #     test_mark: 'nightly_models_ops'
+  #     test_group_cnt: 4
+  #     test_group_ids: '[1,2,3,4]'
+  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
+  #     runs-on: '[{"runs-on": "n150"}]'
+
+  # test_sweeps:
+  #   needs:
+  #     - docker-build
+  #     - build
+  #   uses: ./.github/workflows/test.yml
+  #   secrets: inherit
+  #   with:
+  #     test_mark: 'nightly_sweeps'
+  #     test_group_cnt: 4
+  #     test_group_ids: '[1,2,3,4]'
+  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
+  #     runs-on: '[{"runs-on": "n150"}]'
+  #     operators: ${{ github.event.inputs.operators }}
+    
+  # fail-notify:
+  #   if: always()
+  #   needs:
+  #     - docker-build
+  #     - build
+  #     - test_full_model_passing
+  #     - perf-benchmark
+  #   runs-on: Ubuntu-latest
+  #   outputs:
+  #     is-main: ${{ steps.branch-check.outputs.IS_MAIN }}
+  #     failed: ${{ steps.check.outputs.failure }}
+  #   steps:
+  #     - name: Check if branch is main
+  #       id: branch-check
+  #       run: echo "IS_MAIN=$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
+  #     - name: Check if the needed jobs succeeded or failed
+  #       id: check
+  #       uses: re-actors/alls-green@release/v1
+  #       with:
+  #         jobs: ${{ toJSON(needs) }}
+
+  # fail-send-msg:
+  #   if: always()
+  #   needs:
+  #     - fail-notify
+  #   runs-on: Ubuntu-latest
+  #   steps:
+  #     - name: Send Fail Notification
+  #       if: ${{ needs.fail-notify.outputs.failed == 'true' && needs.fail-notify.outputs.is-main == 'true' }}
+  #       uses: slackapi/slack-github-action@v1.26.0
+  #       with:
+  #         payload: |
+  #           {
+  #             "text": "Bad bad nightly: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}>",
+  #             "channel": "C08HFLL9L56"
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NIGHTLY_FAIL }}
