Hang.

diff --git a/.github/workflows/perf-benchmark-sub.yml b/.github/workflows/perf-benchmark-sub.yml
--- a/.github/workflows/perf-benchmark-sub.yml
+++ b/.github/workflows/perf-benchmark-sub.yml
@@ -18,19 +18,19 @@ jobs:
       fail-fast: false
       matrix:
         build: [
-          { runs-on: "n150", name: "mnist_linear",             dir: "MNISTLinear",                  ts: 'na',             bs: 32,  lp: 32, df: 'float32'   },
-          { runs-on: "n150", name: "resnet50_hf",              dir: "ResNetForImageClassification", ts: 'classification', bs: 8,   lp: 32, df: 'bfloat16'  },
+          { runs-on: "hang", name: "mnist_linear",             dir: "MNISTLinear",                  ts: 'na',             bs: 32,  lp: 32, df: 'float32'   },
+          { runs-on: "hang", name: "resnet50_hf",              dir: "ResNetForImageClassification", ts: 'classification', bs: 8,   lp: 32, df: 'bfloat16'  },
           # { runs-on: "n150", name: "resnet50_hf_config",              dir: "ResNetForImageClassificationConfig", ts: 'classification', bs: 8,  lp: 32, df: 'bfloat16' }, It will be added to CI later.
-          { runs-on: "n150", name: "llama",                    dir: "LlamaModel",                   ts: 'na',             bs: 1,   lp: 32, df: 'float32',  },
-          { runs-on: "n150", name: "mobilenetv2_basic",        dir: "MobileNetv2Basic",             ts: 'classification', bs: 8,   lp: 32, df: 'bfloat16', },
-          { runs-on: "n150", name: "efficientnet_timm",        dir: "EfficientNetTimmB0",           ts: 'classification', bs: 6,   lp: 32, df: 'bfloat32', },
-          { runs-on: "n150", name: "segformer",                dir: "Segformer",                    ts: 'na',             bs: 1,   lp: 32, df: 'float32',  },
-          { runs-on: "n150", name: "vit_base",                 dir: "ViTBase",                      ts: 'classification', bs: 8,   lp: 32, df: 'float32',  },
-          { runs-on: "n150", name: "vovnet_osmr",              dir: "VovnetOSMR",                   ts: 'classification', bs: 16,  lp: 32, df: 'bfloat16', },
-          { runs-on: "n150", name: "yolo_v4",                  dir: "YOLOv4",                       ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
-          { runs-on: "n150", name: "yolo_v8",                  dir: "YOLOv8",                       ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
-          { runs-on: "n150", name: "yolo_v9",                  dir: "YOLOv9",                       ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
-          { runs-on: "n150", name: "yolo_v10",                 dir: "YOLOv10",                      ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
+          { runs-on: "hang", name: "llama",                    dir: "LlamaModel",                   ts: 'na',             bs: 1,   lp: 32, df: 'float32',  },
+          { runs-on: "hang", name: "mobilenetv2_basic",        dir: "MobileNetv2Basic",             ts: 'classification', bs: 8,   lp: 32, df: 'bfloat16', },
+          { runs-on: "hang", name: "efficientnet_timm",        dir: "EfficientNetTimmB0",           ts: 'classification', bs: 6,   lp: 32, df: 'bfloat32', },
+          { runs-on: "hang", name: "segformer",                dir: "Segformer",                    ts: 'na',             bs: 1,   lp: 32, df: 'float32',  },
+          { runs-on: "hang", name: "vit_base",                 dir: "ViTBase",                      ts: 'classification', bs: 8,   lp: 32, df: 'float32',  },
+          { runs-on: "hang", name: "vovnet_osmr",              dir: "VovnetOSMR",                   ts: 'classification', bs: 16,  lp: 32, df: 'bfloat16', },
+          { runs-on: "hang", name: "yolo_v4",                  dir: "YOLOv4",                       ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
+          { runs-on: "hang", name: "yolo_v8",                  dir: "YOLOv8",                       ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
+          { runs-on: "hang", name: "yolo_v9",                  dir: "YOLOv9",                       ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
+          { runs-on: "hang", name: "yolo_v10",                 dir: "YOLOv10",                      ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', },
           # { runs-on: "n150", name: "unet",                     dir: "UNet",                         ts: 'na',             bs: 1,   lp: 32, df: 'bfloat16', }
         ]
     runs-on:
@@ -146,21 +146,28 @@ jobs:
         source env/activate
         mkdir -p ${{ steps.strings.outputs.perf_report_path }}
         python forge/test/benchmark/benchmark.py -m ${{ matrix.build.name }} -ts ${{ matrix.build.ts }} -bs ${{ matrix.build.bs }} -df ${{ matrix.build.df }} -lp ${{ matrix.build.lp }} -o ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json
-        python forge/test/benchmark/device_perf.py -ct ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir.mlir
+        # python forge/test/benchmark/device_perf.py -ct ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir.mlir
 
-    - name: Install and run TTRT
-      shell: bash
-      run: |
-        source env/activate
-        pip install ttrt*.whl --force-reinstall
-        pip install torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
-        echo "save artifacts"
-        ttrt query --save-artifacts
-        if [ -z "${{ matrix.build.allow-fail }}" ]; then
-          ./.github/workflows/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}_ttnn.mlir
-        else
-          ./.github/workflows/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}_ttnn.mlir || true
-        fi
+    # - name: Install and run TTRT
+    #   shell: bash
+    #   run: |
+    #     source env/activate
+    #     pip install ttrt*.whl --force-reinstall
+    #     pip install torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
+    #     echo "save artifacts"
+    #     ttrt query --save-artifacts
+    #     if [ -z "${{ matrix.build.allow-fail }}" ]; then
+    #       ./.github/workflows/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}_ttnn.mlir
+    #     else
+    #       ./.github/workflows/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json ${{ steps.strings.outputs.perf_report_path }}/benchmark_forge_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}_ttnn.mlir || true
+    #     fi
+
+    - name: Upload Debug Logs
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ matrix.build.runs-on }}_${{ matrix.build.image }}_${{ matrix.build.suite }}_debug_logs
+        path: /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/generated/
 
     - name: Upload Perf Report
       uses: actions/upload-artifact@v4
