Changes slim_wheel to slim

diff --git a/.github/workflows/test-sub.yml b/.github/workflows/test-sub.yml
--- a/.github/workflows/test-sub.yml
+++ b/.github/workflows/test-sub.yml
@@ -77,7 +77,7 @@ jobs:
     continue-on-error: ${{ inputs.allow-fail }}
 
     container:
-      image: ${{ (inputs.test_mark == 'slim_wheel') && 'ghcr.io/tenstorrent/tt-forge-fe/tt-forge-fe-base-ubuntu-22-04:latest' || inputs.docker-image }}
+      image: ${{ (inputs.test_mark == 'slim') && 'ghcr.io/tenstorrent/tt-forge-fe/tt-forge-fe-base-ubuntu-22-04:latest' || inputs.docker-image }}
       options: --device /dev/tenstorrent/0
       volumes:
         - /dev/hugepages:/dev/hugepages
@@ -192,48 +192,48 @@ jobs:
           mkdir -p reports
 
           set +e
-          pytest -m slim_wheel -sv forge/test/test_slim_wheel.py \
-                --junit-xml=${{ steps.strings.outputs.test_report_path }}_slim_wheel
-          slim_wheel_exit_code=$?
+          pytest -m slim -sv forge/test/test_slim.py \
+                --junit-xml=${{ steps.strings.outputs.test_report_path }}_slim
+          slim_exit_code=$?
 
           if [ -f "crashed_pytest.log" ]; then
             echo "Creating crash summary for slim wheel tests..."
             echo "### Crashed slim wheel tests:" >>$GITHUB_STEP_SUMMARY
             cat crashed_pytest.log >>$GITHUB_STEP_SUMMARY
-            mv crashed_pytest.log crashed_pytest_slim_wheel.log
+            mv crashed_pytest.log crashed_pytest_slim.log
           fi
 
-          if [ $slim_wheel_exit_code -ne 0 ]; then
-            echo "Slim wheel tests failed with exit code $slim_wheel_exit_code"
-            exit $slim_wheel_exit_code
+          if [ $slim_exit_code -ne 0 ]; then
+            echo "Slim wheel tests failed with exit code $slim_exit_code"
+            exit $slim_exit_code
           fi
 
       - name: Upload Slim Wheel Test Log
         uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
-          name: slim_wheel-test-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
+          name: slim-test-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
           path: pytest.log
 
       - name: Upload Slim Wheel Test Crash Log
         uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
-          name: slim_wheel-test-crash-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
-          path: crashed_pytest_slim_wheel.log
+          name: slim-test-crash-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
+          path: crashed_pytest_slim.log
 
       - name: Upload Slim Wheel Test Report
         uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
-          name: slim_wheel-test-reports-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ steps.fetch-job-id.outputs.job_id }}
-          path: ${{ steps.strings.outputs.test_report_path }}_slim_wheel
+          name: slim-test-reports-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ steps.fetch-job-id.outputs.job_id }}
+          path: ${{ steps.strings.outputs.test_report_path }}_slim
 
       - name: Show Slim Wheel Test Report
         uses: mikepenz/action-junit-report@v5
         if: success() || failure()
         with:
-          report_paths: ${{ steps.strings.outputs.test_report_path }}_slim_wheel
+          report_paths: ${{ steps.strings.outputs.test_report_path }}_slim
           check_name: TT-Forge-FE Slim Wheel Tests
           comment: false
           updateComment: false
