[Deps] Adds slim-wheel test and streamlines core-requirement

diff --git a/.github/workflows/test-sub.yml b/.github/workflows/test-sub.yml
--- a/.github/workflows/test-sub.yml
+++ b/.github/workflows/test-sub.yml
@@ -161,62 +161,62 @@ jobs:
         shell: bash
         run: |
           source env/activate
-          echo "Collecting sanity tests..."
+          echo "Collecting slim wheel tests..."
           pytest --splits 1 \
                --group 1 \
                --splitting-algorithm least_duration \
-               -m "sanity" --collect-only -q forge/test/test_sanity.py \
-                | sed -n '/^Collected tests /,/^collected /p' | sed '/^[Cc]ollected /d' >.pytest_sanity_tests_to_run
+               -m "slim_wheel" --collect-only -q forge/test/test_slim_wheel.py \
+                | sed -n '/^Collected tests /,/^collected /p' | sed '/^[Cc]ollected /d' >.pytest_slim_wheel_tests_to_run
 
-          echo "Collected sanity tests."
-          cat .pytest_sanity_tests_to_run
+          echo "Collected slim wheel tests."
+          cat .pytest_slim_wheel_tests_to_run
 
           set +e
           python .github/workflows/test_runner.py  \
-               --junit-xml=${{ steps.strings.outputs.test_report_path }}_sanity \
+               --junit-xml=${{ steps.strings.outputs.test_report_path }}_slim_wheel \
                --log-memory-usage \
                $(if [ "${{inputs.continue-on-crash}}" = "true" ]; then echo "--continue-after-crash"; fi)
-          sanity_exit_code=$?
+          slim_wheel_exit_code=$?
 
           if [ -f "crashed_pytest.log" ]; then
-            echo "Creating crash summary for sanity tests..."
-            echo "### Crashed sanity tests:" >>$GITHUB_STEP_SUMMARY
+            echo "Creating crash summary for slim wheel tests..."
+            echo "### Crashed slim wheel tests:" >>$GITHUB_STEP_SUMMARY
             cat crashed_pytest.log >>$GITHUB_STEP_SUMMARY
-            mv crashed_pytest.log crashed_pytest_sanity.log
+            mv crashed_pytest.log crashed_pytest_slim_wheel.log
           fi
 
-          if [ $sanity_exit_code -ne 0 ]; then
-            echo "Sanity tests failed with exit code $sanity_exit_code"
-            exit $sanity_exit_code
+          if [ $slim_wheel_exit_code -ne 0 ]; then
+            echo "Slim wheel tests failed with exit code $slim_wheel_exit_code"
+            exit $slim_wheel_exit_code
           fi
 
-      - name: Upload Sanity Test Log
+      - name: Upload Slim Wheel Test Log
         uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
-          name: sanity-test-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
+          name: slim_wheel-test-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
           path: pytest.log
 
-      - name: Upload Sanity Test Crash Log
+      - name: Upload Slim Wheel Test Crash Log
         uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
-          name: sanity-test-crash-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
-          path: crashed_pytest_sanity.log
+          name: slim_wheel-test-crash-log-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ inputs.test_mark }}-${{ steps.fetch-job-id.outputs.job_id }}
+          path: crashed_pytest_slim_wheel.log
 
-      - name: Upload Sanity Test Report
+      - name: Upload Slim Wheel Test Report
         uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
-          name: sanity-test-reports-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ steps.fetch-job-id.outputs.job_id }}
-          path: ${{ steps.strings.outputs.test_report_path }}_sanity
+          name: slim_wheel-test-reports-${{ matrix.build.runs-on }}-${{ matrix.test_group_id }}-${{ steps.fetch-job-id.outputs.job_id }}
+          path: ${{ steps.strings.outputs.test_report_path }}_slim_wheel
 
-      - name: Show Sanity Test Report
+      - name: Show Slim Wheel Test Report
         uses: mikepenz/action-junit-report@v5
         if: success() || failure()
         with:
-          report_paths: ${{ steps.strings.outputs.test_report_path }}_sanity
-          check_name: TT-Forge-FE Sanity Tests
+          report_paths: ${{ steps.strings.outputs.test_report_path }}_slim_wheel
+          check_name: TT-Forge-FE Slim Wheel Tests
           comment: false
           updateComment: false
           detailed_summary: true
