redo collect on error with verbose output

diff --git a/.github/workflows/test-sub.yml b/.github/workflows/test-sub.yml
--- a/.github/workflows/test-sub.yml
+++ b/.github/workflows/test-sub.yml
@@ -164,17 +164,26 @@ jobs:
         run: |
           source env/activate
           echo "Collecting tests for group ${{ matrix.test_group_id }} with mark '${{ inputs.test_mark }}'..."
+          set +e
           pytest --splits ${{ inputs.test_group_cnt }} \
                --group ${{ matrix.test_group_id }} \
                --splitting-algorithm least_duration \
                -m "${{ inputs.test_mark }}" --collect-only -q \
                 | sed -n '/^Collected tests /,/^collected /p' | sed '/^[Cc]ollected /d' >.pytest_tests_to_run
 
+          if [ $? -ne 0 ]; then
+            echo "Failed to collect tests. Doing dry run..."
+            set -e
+            pytest --splits ${{ inputs.test_group_cnt }} \
+                --group ${{ matrix.test_group_id }} \
+                --splitting-algorithm least_duration \
+                -m "${{ inputs.test_mark }}" --collect-only -svv
+            exit 1
+          fi
           echo "Collected tests."
           # enable next line for debugging
           # cat .pytest_tests_to_run
 
-          set +e
           python .github/workflows/test_runner.py  \
                --junit-xml=${{ steps.strings.outputs.test_report_path }} \
                --log-memory-usage \
